.class public Lcom/android/settings/AGPSFunctionSwitchList;
.super Landroid/app/Activity;
.source "AGPSFunctionSwitchList.java"

# interfaces
.implements Landroid/view/View$OnClickListener;


# static fields
.field public static mSecProperties:Ljava/util/Properties;

.field private static mbtnAgpsDefaultValue:Landroid/widget/Button;


# instance fields
.field mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

.field mRadioButton2:Lcom/sec/android/touchwiz/widget/TwRadioButton;

.field mRadioButton3:Lcom/sec/android/touchwiz/widget/TwRadioButton;

.field private mtvAgpsDefaultValueNote:Landroid/widget/TextView;

.field private mtvAgpsDefaultValueTitle:Landroid/widget/TextView;


# direct methods
.method static constructor <clinit>()V
    .locals 1

    .prologue
    .line 36
    const/4 v0, 0x0

    sput-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mbtnAgpsDefaultValue:Landroid/widget/Button;

    return-void
.end method

.method public constructor <init>()V
    .locals 1

    .prologue
    const/4 v0, 0x0

    .line 27
    invoke-direct {p0}, Landroid/app/Activity;-><init>()V

    .line 37
    iput-object v0, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueTitle:Landroid/widget/TextView;

    .line 38
    iput-object v0, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueNote:Landroid/widget/TextView;

    return-void
.end method

.method private save()V
    .locals 5

    .prologue
    .line 258
    :try_start_0
    new-instance v1, Ljava/io/File;

    const-string v3, "/data/data/com.android.angryGps/secgps.conf"

    invoke-direct {v1, v3}, Ljava/io/File;-><init>(Ljava/lang/String;)V

    .line 259
    .local v1, file:Ljava/io/File;
    new-instance v2, Ljava/io/FileOutputStream;

    invoke-direct {v2, v1}, Ljava/io/FileOutputStream;-><init>(Ljava/io/File;)V

    .line 261
    .local v2, stream:Ljava/io/FileOutputStream;
    sget-object v3, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v4, "Generated by AngryGPS & setting."

    invoke-virtual {v3, v2, v4}, Ljava/util/Properties;->store(Ljava/io/OutputStream;Ljava/lang/String;)V

    .line 262
    invoke-virtual {v2}, Ljava/io/FileOutputStream;->close()V
    :try_end_0
    .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_0

    .line 266
    .end local v1           #file:Ljava/io/File;
    .end local v2           #stream:Ljava/io/FileOutputStream;
    :goto_0
    return-void

    .line 263
    :catch_0
    move-exception v3

    move-object v0, v3

    .line 264
    .local v0, e:Ljava/io/IOException;
    const-string v3, "AGPSFunctionSwitch"

    const-string v4, "Could not open GPS configuration file in save : /data/data/com.android.angryGps/secgps.conf"

    invoke-static {v3, v4}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    goto :goto_0
.end method

.method private setDefaultParameters()V
    .locals 6

    .prologue
    const/4 v4, 0x0

    const-string v5, "0"

    const-string v3, "1"

    .line 269
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "SESSION_TYPE"

    const-string v2, "1"

    invoke-virtual {v0, v1, v3}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 270
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "OPERATION_TEST_MODE"

    const-string v2, "0"

    invoke-virtual {v0, v1, v5}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 271
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "OPERATION_MODE"

    const-string v2, "MSBASED"

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 272
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "SSL"

    const-string v2, "1"

    invoke-virtual {v0, v1, v3}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 273
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "AGPS_MODE"

    const-string v2, "0"

    invoke-virtual {v0, v1, v5}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 274
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "START_MODE"

    const-string v2, "1"

    invoke-virtual {v0, v1, v3}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 275
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "GPS_LOGGING"

    const-string v2, "1"

    invoke-virtual {v0, v1, v3}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 276
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "SUPL_PORT"

    const/16 v2, 0x1c6b

    invoke-static {v2}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 277
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "ENABLE_XTRA"

    const-string v2, "1"

    invoke-virtual {v0, v1, v3}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 278
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "SUPL_HOST"

    const-string v2, "221.176.0.55"

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 279
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "TIMEOUT"

    const-string v2, "255"

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 280
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "SERVER_MODE_QCOM"

    invoke-static {v4}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 281
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "SSL_TYPE"

    invoke-static {v4}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 282
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "DYNAMIC_ACCURACY"

    const/4 v2, 0x1

    invoke-static {v2}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 283
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "ACCURACY"

    const/16 v2, 0x32

    invoke-static {v2}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 285
    invoke-direct {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->save()V

    .line 286
    return-void
.end method


# virtual methods
.method public GPSSetDefaultVaule()V
    .locals 8

    .prologue
    const-string v5, "/data/data/com.android.angryGps/secgps.conf"

    const-string v7, "AGPSFunctionSwitch"

    .line 221
    const-string v5, "AGPSFunctionSwitch"

    const-string v5, "Load the configuration file"

    invoke-static {v7, v5}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 226
    const/4 v3, 0x0

    .line 227
    .local v3, fsuccess:Z
    new-instance v5, Ljava/util/Properties;

    invoke-direct {v5}, Ljava/util/Properties;-><init>()V

    sput-object v5, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    .line 230
    :try_start_0
    new-instance v5, Ljava/io/File;

    const-string v6, "/data/data/com.android.angryGps"

    invoke-direct {v5, v6}, Ljava/io/File;-><init>(Ljava/lang/String;)V

    invoke-virtual {v5}, Ljava/io/File;->mkdir()Z

    move-result v0

    .line 231
    .local v0, dirsuccess:Z
    if-eqz v0, :cond_1

    .line 232
    const-string v5, "AGPSFunctionSwitch"

    const-string v6, "Directory: /data/data/com.android.angryGps created"

    invoke-static {v5, v6}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 233
    new-instance v2, Ljava/io/File;

    const-string v5, "/data/data/com.android.angryGps/secgps.conf"

    invoke-direct {v2, v5}, Ljava/io/File;-><init>(Ljava/lang/String;)V

    .line 234
    .local v2, file:Ljava/io/File;
    if-eqz v2, :cond_0

    invoke-virtual {v2}, Ljava/io/File;->exists()Z

    move-result v5

    if-nez v5, :cond_0

    .line 235
    invoke-virtual {v2}, Ljava/io/File;->createNewFile()Z

    move-result v3

    .line 241
    :cond_0
    :goto_0
    new-instance v4, Ljava/io/FileInputStream;

    invoke-direct {v4, v2}, Ljava/io/FileInputStream;-><init>(Ljava/io/File;)V

    .line 242
    .local v4, stream:Ljava/io/FileInputStream;
    sget-object v5, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    invoke-virtual {v5, v4}, Ljava/util/Properties;->load(Ljava/io/InputStream;)V

    .line 243
    invoke-virtual {v4}, Ljava/io/FileInputStream;->close()V

    .line 246
    invoke-direct {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->setDefaultParameters()V

    .line 252
    .end local v0           #dirsuccess:Z
    .end local v2           #file:Ljava/io/File;
    .end local v4           #stream:Ljava/io/FileInputStream;
    :goto_1
    return-void

    .line 238
    .restart local v0       #dirsuccess:Z
    :cond_1
    new-instance v2, Ljava/io/File;

    const-string v5, "/data/data/com.android.angryGps/secgps.conf"

    invoke-direct {v2, v5}, Ljava/io/File;-><init>(Ljava/lang/String;)V
    :try_end_0
    .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_0

    .restart local v2       #file:Ljava/io/File;
    goto :goto_0

    .line 248
    .end local v0           #dirsuccess:Z
    .end local v2           #file:Ljava/io/File;
    :catch_0
    move-exception v5

    move-object v1, v5

    .line 249
    .local v1, e:Ljava/io/IOException;
    const-string v5, "AGPSFunctionSwitch"

    const-string v5, "Could not open GPS configuration file in load : /data/data/com.android.angryGps/secgps.conf"

    invoke-static {v7, v5}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    .line 250
    invoke-direct {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->setDefaultParameters()V

    goto :goto_1
.end method

.method public onClick(Landroid/view/View;)V
    .locals 9
    .parameter "v"

    .prologue
    const/4 v6, 0x1

    const/4 v5, 0x0

    const-string v8, "OperationTestMode"

    const-string v3, "AGPSFunctionSwitch"

    const-string v7, "OperationMode"

    .line 136
    const/4 v1, 0x0

    .line 137
    .local v1, OperationTestMode:I
    const/4 v0, 0x0

    .line 139
    .local v0, OperationMode:I
    invoke-virtual {p1}, Landroid/view/View;->getId()I

    move-result v2

    packed-switch v2, :pswitch_data_0

    .line 201
    :pswitch_0
    const-string v2, "AGPSFunctionSwitch"

    const-string v2, "default"

    invoke-static {v3, v2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 202
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$Secure;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 204
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v8, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 205
    if-nez v1, :cond_0

    .line 206
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v7, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 207
    if-nez v0, :cond_0

    .line 208
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v7, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 212
    :cond_0
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->finish()V

    .line 217
    :goto_0
    return-void

    .line 142
    :pswitch_1
    const-string v2, "AGPSFunctionSwitch"

    const-string v2, "agps_on_for_home_network"

    invoke-static {v3, v2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 143
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$Secure;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 145
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v8, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 146
    if-nez v1, :cond_1

    .line 147
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v7, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 148
    if-nez v0, :cond_1

    .line 149
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v7, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 152
    :cond_1
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->finish()V

    goto :goto_0

    .line 156
    :pswitch_2
    const-string v2, "AGPSFunctionSwitch"

    const-string v2, "agps_on_for_all_network"

    invoke-static {v3, v2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 157
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    const/4 v4, 0x2

    invoke-static {v2, v3, v4}, Landroid/provider/Settings$Secure;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 159
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v8, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 160
    if-nez v1, :cond_2

    .line 161
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v7, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 162
    if-nez v0, :cond_2

    .line 163
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v7, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 166
    :cond_2
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->finish()V

    goto :goto_0

    .line 170
    :pswitch_3
    const-string v2, "AGPSFunctionSwitch"

    const-string v2, "agps_off"

    invoke-static {v3, v2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 171
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    const/4 v4, 0x3

    invoke-static {v2, v3, v4}, Landroid/provider/Settings$Secure;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 173
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v8, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 174
    if-nez v1, :cond_3

    .line 175
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v7, v5}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 177
    :cond_3
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->finish()V

    goto/16 :goto_0

    .line 181
    :pswitch_4
    const-string v2, "AGPSFunctionSwitch"

    const-string v2, "agps_default_value"

    invoke-static {v3, v2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 182
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$Secure;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 183
    const v2, 0x7f0b0006

    invoke-virtual {p0, v2}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v2

    check-cast v2, Lcom/sec/android/touchwiz/widget/TwRadioButton;

    iput-object v2, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    .line 184
    iget-object v2, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v2, v6}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setChecked(Z)V

    .line 186
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v8, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 187
    if-nez v1, :cond_4

    .line 188
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v7, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 190
    :cond_4
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "ServerCustomUrl"

    const-string v4, "221.176.0.55"

    invoke-static {v2, v3, v4}, Landroid/provider/Settings$System;->putString(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;)Z

    .line 191
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "ServerCustomPort"

    const/16 v4, 0x1c6b

    invoke-static {v2, v3, v4}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 195
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->GPSSetDefaultVaule()V

    .line 197
    invoke-virtual {p1}, Landroid/view/View;->invalidate()V

    goto/16 :goto_0

    .line 139
    nop

    :pswitch_data_0
    .packed-switch 0x7f0b0006
        :pswitch_1
        :pswitch_2
        :pswitch_3
        :pswitch_0
        :pswitch_0
        :pswitch_4
    .end packed-switch
.end method

.method public onCreate(Landroid/os/Bundle;)V
    .locals 6
    .parameter "savedInstanceState"

    .prologue
    const/16 v5, 0x8

    const/4 v4, 0x1

    .line 64
    invoke-super {p0, p1}, Landroid/app/Activity;->onCreate(Landroid/os/Bundle;)V

    .line 65
    const/high16 v1, 0x7f03

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->setContentView(I)V

    .line 67
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v1

    const-string v2, "agps_function_switch"

    invoke-static {v1, v2, v4}, Landroid/provider/Settings$Secure;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 68
    .local v0, agps_function_switch_mode:I
    const-string v1, "AGPSFunctionSwitch"

    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    const-string v3, "onCreate : Settings.Secure.AGPS_FUNCTION_SWITCH : "

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    invoke-static {v1, v2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 71
    const v1, 0x7f0b0006

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Lcom/sec/android/touchwiz/widget/TwRadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    .line 72
    const v1, 0x7f0b0007

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Lcom/sec/android/touchwiz/widget/TwRadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    .line 73
    const v1, 0x7f0b0008

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Lcom/sec/android/touchwiz/widget/TwRadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    .line 75
    const v1, 0x7f0b000b

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/Button;

    sput-object v1, Lcom/android/settings/AGPSFunctionSwitchList;->mbtnAgpsDefaultValue:Landroid/widget/Button;

    .line 76
    const v1, 0x7f0b0009

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/TextView;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueTitle:Landroid/widget/TextView;

    .line 77
    const v1, 0x7f0b000a

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/TextView;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueNote:Landroid/widget/TextView;

    .line 80
    packed-switch v0, :pswitch_data_0

    .line 91
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, v4}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setChecked(Z)V

    .line 95
    :goto_0
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, p0}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    .line 96
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, p0}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    .line 97
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, p0}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    .line 99
    sget-object v1, Lcom/android/settings/AGPSFunctionSwitchList;->mbtnAgpsDefaultValue:Landroid/widget/Button;

    invoke-virtual {v1, v5}, Landroid/widget/Button;->setVisibility(I)V

    .line 100
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueTitle:Landroid/widget/TextView;

    invoke-virtual {v1, v5}, Landroid/widget/TextView;->setVisibility(I)V

    .line 101
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueNote:Landroid/widget/TextView;

    invoke-virtual {v1, v5}, Landroid/widget/TextView;->setVisibility(I)V

    .line 102
    sget-object v1, Lcom/android/settings/AGPSFunctionSwitchList;->mbtnAgpsDefaultValue:Landroid/widget/Button;

    invoke-virtual {v1, p0}, Landroid/widget/Button;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    .line 105
    return-void

    .line 82
    :pswitch_0
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, v4}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setChecked(Z)V

    goto :goto_0

    .line 85
    :pswitch_1
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, v4}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setChecked(Z)V

    goto :goto_0

    .line 88
    :pswitch_2
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, v4}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setChecked(Z)V

    goto :goto_0

    .line 80
    nop

    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_0
        :pswitch_1
        :pswitch_2
    .end packed-switch
.end method

.method protected onResume()V
    .locals 5

    .prologue
    const/4 v4, 0x1

    .line 109
    invoke-super {p0}, Landroid/app/Activity;->onResume()V

    .line 111
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v1

    const-string v2, "agps_function_switch"

    invoke-static {v1, v2, v4}, Landroid/provider/Settings$Secure;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 112
    .local v0, agps_function_switch_mode:I
    const-string v1, "AGPSFunctionSwitch"

    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    const-string v3, "onResume : Settings.Secure.AGPS_FUNCTION_SWITCH : "

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    invoke-static {v1, v2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 114
    const v1, 0x7f0b0006

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Lcom/sec/android/touchwiz/widget/TwRadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    .line 115
    const v1, 0x7f0b0007

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Lcom/sec/android/touchwiz/widget/TwRadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    .line 116
    const v1, 0x7f0b0008

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Lcom/sec/android/touchwiz/widget/TwRadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    .line 118
    packed-switch v0, :pswitch_data_0

    .line 129
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, v4}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setChecked(Z)V

    .line 133
    :goto_0
    return-void

    .line 120
    :pswitch_0
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, v4}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setChecked(Z)V

    goto :goto_0

    .line 123
    :pswitch_1
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, v4}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setChecked(Z)V

    goto :goto_0

    .line 126
    :pswitch_2
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Lcom/sec/android/touchwiz/widget/TwRadioButton;

    invoke-virtual {v1, v4}, Lcom/sec/android/touchwiz/widget/TwRadioButton;->setChecked(Z)V

    goto :goto_0

    .line 118
    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_0
        :pswitch_1
        :pswitch_2
    .end packed-switch
.end method
